app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



// Public Routes
Route::get('/', array('uses' => 'PostController@index'));

Route::get('home', 'WelcomeController@index');

Route::resource('login', 'LoginController');

Route::resource('post', 'PostController');

Route::get('signup', array('uses' => 'LoginController@signup', 'as' => 'signup'));

Route::post('signup', array('uses' => 'LoginController@doSignup', 'as' => 'signup'));

Route::post('image', array('uses' => 'ImageController@postImage'));


// Protected Routes
Route::group(['before' => 'auth'], function()
{		
	Route::resource('user', 'UserController');

	Route::resource('category', 'CategoryController');

	Route::resource('tag', 'TagController');

	Route::resource('administrator', 'AdministratorController');

});

resources/views/visiter/blog.blade.php
@extends('layouts.visiter')

@section('content')
<!-- Welcome Message -->
<div class="row">
	<div class="col-lg-12" align="right">
		<h1 class="page-header">Azur Blog
			<small>Welcome visiter!</small>
		</h1>
	</div>
</div>
<!-- New entry-->
<div class="jumbotron">
	{!! Form::open(array('route' => array('post.store'),  'files' => true)) !!}
	<fieldset>
		<div class="form-group">
			<label for="title" class="col-lg-2 control-label">Title:</label>
			<div class="col-lg-10">
				<input type="text" name="title" class="form-control" id="title" value="{{$title}}" placeholder="This is my new post">
			</div>
		</div>
		<div class="form-group">
			<label for="content" class="col-lg-2 control-label" >Content:</label>
			<div class="col-lg-10">
				<textarea class="form-control" name="content" rows="3" id="textArea" value="{{$content}}" placeholder="About Azurlingua..."></textarea>
				<span class="help-block">Write a cool post!</span>
			</div>
		</div>
		<div class="form-group">
			<label for="select" class="col-lg-2 control-label">Categories:</label>
			<div class="col-lg-10">
				{!! Form::select('categories[]',$category_options,null,array('multiple'=>'multiple', 'class'=>'form-control')) !!}
				<span class="help-block">Select as many as you want!</span>
			</div>
		</div>
		<div class="form-group">
			<label for="picture" class="col-lg-2 control-label">Picture:</label>
			<div class="col-lg-10">	
				<div style="text-align:left;" class="content-box">
					<div id="picbox" class="clear" style="padding-top:0px;padding-bottom:10px;">
						<br/ >
						<img id="uploadThumbnail" src="http://placehold.it/200x150" />	
					</div>
					<div class="clear">
						<button id="upload-btn" class="btn btn-primary btn-large clearfix"><i class="fa fa-cloud-upload"></i> Select file</button>
						<br />
						<div id="errormsg" class="clearfix redtext"><small>(JPG, PNG, GIF)</small></div>
					</div>
				</div>
			</div>
		</div>

		<div class="form-group" align="right">
			<div class="col-lg-10 col-lg-offset-2">
				<br>
				{!! Form::reset('Cancel',  array('class' => 'btn btn-danger')) !!}
				{!! Form::submit('Done',  array('class' => 'btn btn-success')) !!}
			</div>
		</div>

	</fieldset>
	{!! Form::close() !!}
</div>
<!-- Posts -->
@foreach($posts as $post)
<div class="row">
	<div class="col-md-7">
		<div class="clear" style="padding-top:0px;padding-bottom:10px;">
			<a href="{!! route('post.show', array('post' => $post->id) ) !!}">
				@if ( $post->picture_id != 'null' ) 
					<img id="post_picture" class="img-responsive" src="" />
					<!-- {!! Cloudy::show( $post->picture_id,  array('width' => 900, 'height' => 300, 'crop' => 'fill', 'radius' => 10)) !!} -->
					<!-- {!! Cloudy::show( 'laravel-900x300_yfmaf5',  array('width' => 900, 'height' => 300, 'crop' => 'fill', 'radius' => 10)) !!} -->
				@else
					<img id="post_picture" class="img-responsive" src="" />
				@endif
			</a>
		</div>
	</div>
	<div class="col-md-5">
		<h2>{!! $post->title !!}</h2>
		<h4>[By {!! $post->user->username !!}]</h4>
		<h5>Posted on {!! $post->created_at !!}</h5>
		<p>Categories :
			@foreach($post->categories as $category)
				{!! $category->name !!}
			@endforeach
		</p>
		<p>Tagged as :
			@foreach($post->tags as $tag)
				{!! $tag->description !!}
			@endforeach
		</p>
	</div>
</div>
@endforeach 
@stop

resources/views/visiter/post.blade.php
@extends('layouts.visiter')

@section('content')
<!-- Post Title -->
<div class="row">
  <br>
  <div class="col-lg-12" align="left">
    <!-- Title -->
    <h1 class="page-header"> {!! $post->title !!}</h1>
  </div>
</div>
<!-- Post Body -->
<div class="row">
	<!-- Blog Post Content Column -->
	<div class="col-lg-8">
		<!-- Author -->
		<p class="lead">
			by {!! $post->user->username !!}
		</p>
		<!-- Date/Time -->
		<p><span class="glyphicon glyphicon-time"></span> Posted on {!! $post->created_at !!}</p>
		<hr>
		<!-- Post Image --> 
    @if ( $post->picture_id != 'null' )
      <img id="post_picture" class="img-responsive" src="" />
      <!-- <img id="post_picture" class="img-responsive" src="{!! Cloudy::show( $post->picture_id,  array('width' => 900, 'height' => 270, 'crop' => 'fill', 'radius' => 10)) !!}" /> -->
      <!-- <img id="post_picture" class="img-responsive" src="{!! Cloudy::show( 'laravel-900x300_yfmaf5',  array('width' => 900, 'height' => 270, 'crop' => 'fill', 'radius' => 10)) !!}" /> -->
    @else
      <img id="post_picture" class="img-responsive" src="" />
    @endif
    <hr>
    <!-- Post Content -->
    <p class="lead">{!! $post->content !!}</p>
  </div>
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
   <!-- Word Search Well -->
   <div class="well">
    <h4>Word Search</h4>
    <div class="input-group">
      <input type="text" class="form-control">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  </div>
  <!-- Blog Categories -->
  <div class="well">
    <h4>Post Categories</h4>
    <div class="row">
      <div class="col-lg-6">
        <ul class="list-unstyled">
         @foreach($post->categories as $category)
         - {!! $category->name !!}
         @endforeach
       </ul>
     </div>
   </div>
   <!-- /.row -->
 </div>
 <!-- Blog Tags -->
 <div class="well">
  <h4>Post Tags</h4>
  <div class="row">
    <div class="col-lg-6">
      <ul class="list-unstyled">
       @foreach($post->tags as $tag)
       -{!! $tag->description !!}
       @endforeach
     </ul>
   </div>
 </div>
</div>
</div>
</div>

<div id="disqus_thread"></div>
<script type="text/javascript">

  var disqus_shortname = 'avila92';

  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

<script type="text/javascript">

  var disqus_shortname = 'avila92';

  (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());
</script>
@stop